/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";

import islandScene from "../assets/3d/sea_keep_lonely_watcher.glb";

const Island = (props) => {
  const islandRef = useRef();

  const { nodes, materials } = useGLTF(islandScene);

  return (
    <group {...props} dispose={null}>
      <group>
        <group>
          <mesh
        
            geometry={nodes.Fortress_Fortress_0.geometry}
            material={materials.Fortress}
          />
          <mesh
           
            geometry={nodes.Fortress_Fortress_0_1.geometry}
            material={materials.Fortress}
          />
          <mesh
        
            geometry={nodes.Fortress_Fortress_0_2.geometry}
            material={materials.Fortress}
          />
          <mesh
           
            geometry={nodes.Fortress_Environment_0.geometry}
            material={materials.Environment}
          />
          <mesh
     
            geometry={nodes.Fortress_Sand_0.geometry}
            material={materials.Sand}
          />
        </group>
      </group>
      <mesh

        geometry={nodes.Sea_Sea_0.geometry}
        material={materials.material}
      />
      <mesh

        geometry={nodes.Sky_Sky_0.geometry}
        material={materials.material_4}
      />
    </group>
  );
}

export default Island;
